apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: default
  labels:
    application: logging
    component: logstash
data:
  logstash.yml: |
    http.host: "127.0.0.1"
    path.config: /usr/share/logstash/pipeline/
  logstash.conf: |
    input {
      file {
        path => "/tmp/*.log"
        start_position => "beginning"
      }
    }
    output {
      stdout { codec => rubydebug  }
    }
